services:
  db:
    image: postgres:18
    user: root
    environment:
      - POSTGRES_USER=odoo
      - POSTGRES_PASSWORD=odoo19@2025
      - POSTGRES_DB=postgres
    restart: always             # run as a service
    ports:
      - "5432:5432"
    volumes:
        - ./postgresql:/var/lib/postgresql/18/docker      # Important Change: the PGDATA environment variable of the image was changed to be version specific in PostgreSQL 18 and above‚Å†

  odoo19:
    image: odoo:19
    user: root
    depends_on:
      - db
    ports:
      - "10019:8069"
      - "20019:8072" # live chat
    tty: true
    command: --log-level=info --addons-path=/mnt/enterprise-addons,/mnt/extra-addons
    environment:
      - HOST=db
      - USER=odoo
      - PASSWORD=odoo19@2025
      - PIP_BREAK_SYSTEM_PACKAGES=1
      - PYTHONUNBUFFERED=1
    volumes:
      #- /etc/timezone:/etc/timezone:ro
      #- /etc/localtime:/etc/localtime:ro
      - ./entrypoint.sh:/entrypoint.sh
      - ./odoo-enterprise/src/odoo/addons:/mnt/enterprise-addons
      - ./addons:/mnt/extra-addons
      - ./etc:/etc/odoo
    restart: always             # run as a service
  onlyoffice:
    image: onlyoffice/documentserver
    restart: always
    ports:
      - "8081:80"
    volumes:
      - ./onlyoffice/data:/var/www/onlyoffice/Data
      - ./onlyoffice/logs:/var/log/onlyoffice
    environment:
      - JWT_ENABLED=true
      - JWT_SECRET=odoo_onlyoffice_secret
